language: node_js
node_js:
  - 14
services:
  - docker
#before_script:
#  - npm install
jobs:
  include:
    - stage: compile
      if: branch = main
      name: "Compile TypeScript and Lint"
      script:
        - echo "node-common test"
